### ISSUE TITLE
invalid memory address crashing find-lf?

### ISSUE THREAD

**Issue by sudochownrwhoami** [schollz/find-lf#19]
I'm getting the following error and it kills the find-lf server and breaks everything else that relies on the server, any ideas on how I can prevent this from happening?

> [GIN] 2017/09/27 - 11:01:54 | 200 |      735.98µs |       10.0.1.71 | POST     /reversefingerprint
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xb code=0x1 addr=0x0 pc=0x4036ba]
> 
> goroutine 21 [running]:
> panic(0xa50720, 0xc8200100c0)
> 	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
> main.sendFingerprints(0xc820194bd0)
> 	/home/justin/find-lf/server/server.go:278 +0x13da
> created by main.parseFingerprints
> 	/home/justin/find-lf/server/server.go:204 +0x62

**Comment by schollz** [comment]
I think it was maybe related to #20, Can you try now?The gateway is back up.
